name: Conv test

on:
  push:
    branches:
      - Feat/pipeline_conv 
  pull_request:
    branches:
      - Team-BDD
      - Team-DW
      - Team-IA
      - Team-Ref

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Wait for MySQL service to start
        run: sudo systemctl is-active mysql.service

      - name: Run database tests
        run: pytest test_conv.py 